name: app_router_dart
version: "0.1"
author: "Original element - Erik Ringsmuth <erik.ringsmuth@gmail.com>"
description: "Dart port of app-router polymer element"
homepage: "http://erikringsmuth.github.io/app-router/"
dependencies:
  custom_element_apigen: ">= 0.0.2 <0.1.0"
  polymer: ">=0.14.0 <0.16.0"
  web_components: ">=0.7.0 <0.8.0"
dev_dependencies:
  unittest: ">=0.11.0+2 <0.12.0"
environment:
  sdk: '>=1.6.0 <2.0.0'
transformers:
- polymer:

    lint: false
